import numpy as np

In [1]:
import numpy as np


In [2]:
# 1D array - runs scored by one player in 4 mathces
virat_runs = np.array([72, 45, 88, 101])
print(virat_runs)

[ 72  45  88 101]


In [3]:
# 2D array - Rus by 3 playesrs across 3 matches
team_runs = np.array([
    [72, 45, 88],
    [55, 60, 47],
    [30, 75, 50]
])
print(team_runs)

[[72 45 88]
 [55 60 47]
 [30 75 50]]


In [4]:
# 1 D ary from a single tuple - payaer ages
player_ages = np.array((35, 37, 31))
print(player_ages)

[35 37 31]


In [5]:
%autosave 10


Autosaving every 10 seconds


In [8]:
# Specia arrays
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
identity = np.eye(3)
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
empty = np.empty((2, 2))
full = np.full((2, 2),7)
print(empty)
print(full)
print(indetity) # we have not initalises this values so thats ehy it shoes the error 

[[2.12199579e-314 6.95314361e-310]
 [7.37145944e-321 9.90972035e-312]]
[[7 7]
 [7 7]]


NameError: name 'indetity' is not defined

In [11]:
# Creating arrays with range
arr = np.arange(55, 65)
#what we give gap bet two consective elemnets 
# what numply calculates nuber of elements

print(arr, arr[0], arr[5], arr[9])
arr[4] = 99
print(arr[4])

[55 56 57 58 59 60 61 62 63 64] 55 60 64
99


In [15]:
# Baatting avarages (evenly sapced values)
batting_avgs = np.linspace(30, 50, 5)
print(batting_avgs)
# in linspace we ask numpy for a any kind of difference betwwn the values in
# from given range provide any 5 or x values with same rm wahteven formula just give 5 values 
#from the given range

# start at 55
# start at 65
#linspace = have a total of 3 lelements at an equal distance from each other

[30. 35. 40. 45. 50.]


In [18]:
# Random numbers
#Uniform the range we gave to it 
# THEY SHOULD BE UNIFIORMLEY DISTRUBUTED 

Strike_rates = np.random.uniform(100, 200, 10,)
print(Strike_rates)

[166.14754306 171.48463537 162.2914033  188.84158464 190.37723226
 174.40486468 188.72938852 166.01495528 138.74769104 129.26101262]


In [19]:
runs = np.random.randint(1, 151,(2, 3))
print(runs)
# give the random numbers from the 1 to 151 with the output of 2 D array
# (2= rows, 3= columns)


[[ 85  26 102]
 [ 27  85  96]]


In [21]:
# Addition new values to an existing array
arr = np.arange(0, 10)
new_arr_single = np.append(arr, 89)
new_arr_multiple = np.append(arr, [77, 88, 99])
print(arr)
print(new_arr_single)
print(new_arr_multiple)
# we cannot do any changels in the mian array we can add new values in
# the array oly if we crerate a new array and then add(append) the new values with it


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 89]
[ 0  1  2  3  4  5  6  7  8  9 77 88 99]


In [22]:
# Reshaping
marks = np.arange(50, 62)
print(marks)

[50 51 52 53 54 55 56 57 58 59 60 61]


In [23]:
reshaped = marks.reshape(3,4)
print(reshaped)

[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]]
