In [1]:
# vectorization , broadcasting, clicing, cpoy, filering
import numpy as np

In [2]:
# marks of 11 student (roll number 0-10)
marks = np.array([55,68,72,49,83,91,37,65,78,59,88])
print(marks)

[55 68 72 49 83 91 37 65 78 59 88]


In [3]:
#indexing and Slicing
print(marks[8])
print(marks[1:5])
print(marks[0:5])



78
[68 72 49 83]
[55 68 72 49 83]


In [4]:
# Broadcasting (update multiple values)
marks[0:3] = 75
print(marks)

[75 75 75 49 83 91 37 65 78 59 88]


In [5]:
# Vectorization
result = marks + 5
print(result)

[80 80 80 54 88 96 42 70 83 64 93]


In [6]:
# Reset Array
marks - np.array([55, 68, 72, 49, 83, 91, 37, 65, 78, 59, 88])
print(marks)

[75 75 75 49 83 91 37 65 78 59 88]


In [7]:
# Slices and Copy
top_batch = marks[0:5]
print(top_batch)
# printing the values formt he shallow batch

[75 75 75 49 83]


In [8]:
# Modifying slice (affect oringnal)
top_batch[:] = 99
print(top_batch)
print(marks)

[99 99 99 99 99]
[99 99 99 99 99 91 37 65 78 59 88]


In [9]:
# To avoid this, use cpoy()
marks = np.array([55, 68,72, 49, 83, 91,37, 65, 78, 59, 88])
marks_copy = marks.copy()
marks_copy[3] = 99 # it modifie the array but onlyt the deep copy not the main(shallow)
print(marks_copy)
print(marks)

[55 68 72 99 83 91 37 65 78 59 88]
[55 68 72 49 83 91 37 65 78 59 88]


In [11]:
# Conditional Selection
marks = np.array([69, 26, 78, 91, 54, 34])
print(marks)

[69 26 78 91 54 34]


In [13]:
passed = marks >= 35
print(passed) # printfalse/true for each student marks records
#[true, false, true, true, true, false]
print(marks[passed]) # print marsk of the studnent who have pased
# [69: True, 25:false, 78: true, 91: true, 54: true, 34: fsalse]
#[69,78,91,54]

[ True False  True  True  True False]
[69 78 91 54]


In [14]:
# Or directly:
print(marks[marks > 35])

[69 78 91 54]
